plugins { id 'java-library' }

group = 'com.git.bs'

eclipse.project.name = appName + '-demo'

dependencies {
  api project(':core-all')
  implementation project(':bs-res')

  implementation "org.slf4j:slf4j-api:$slf4jVersion"

  compileOnly "org.projectlombok:lombok:$lombokVersion"
  annotationProcessor "org.projectlombok:lombok:$lombokVersion"
}
